Clean up docs and code
SETI/rms-tabulation pull request #10
Opened 2024-07-16 23:53 UTC by rfrenchseti

2024-08-07 00:22 UTC, rfrenchseti commented
Because of the large number of changes, sometimes it's easier to just look at the entire codebase directly, instead of looking at the diffs.

To test this module:

```sh
git clone https://github.com/SETI/rms-tabulation
cd rms-tabulation
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3
>>> from tabulation import Tabulation
>>> ...
```

To create the documentation:

```sh
cd docs
make html
```

then navigate your OS UI (i.e. Mac Finder) to `rms-tabulation/docs/_build/html` and (double-)click on `index.html` to open it in your browser.

2024-09-12 19:37 UTC, mseritan commented
We went through the examples given in the documentation.

For the input of:
`r2 = t2([0,   1,   1.9,  2,   3,   3.9, 4,   5,   6])`
The documentation examples suggest an expected output of:
`array([      0.,  5.,  9.5, 10., 10., 10., 10.,  0.,  0.])`
Our actual output is:
`array([0.  , 2.5 , 4.75, 5.  , 5.  , 5.  , 5.  , 0.  , 0.  ])`

For the input of:
`t3([0,       1,   1.9,   2,     3,     3.9,   4,     5,     6])`
The documentation examples suggest an expected output of:
`array([ 0.  ,  2.5 ,  4.75, -5.  , -5.  , -5.  , -5.  ,  0.  ,  0.  ])`
Our actual output is:
`array([ 0.  , -2.5 , -4.75,  5.  ,  5.  ,  5.  ,  5.  ,  0.  ,  0.  ])`

All other outputs match the suggested outputs in the examples in the documentation.

2024-09-12 19:42 UTC, rfrenchseti commented
> We went through the examples given in the documentation.
> 
> For the input of: `r2 = t2([0, 1, 1.9, 2, 3, 3.9, 4, 5, 6])` The documentation examples suggest an expected output of: `array([ 0., 5., 9.5, 10., 10., 10., 10., 0., 0.])` Our actual output is: `array([0. , 2.5 , 4.75, 5. , 5. , 5. , 5. , 0. , 0. ])`
> 
> For the input of: `t3([0, 1, 1.9, 2, 3, 3.9, 4, 5, 6])` The documentation examples suggest an expected output of: `array([ 0. , 2.5 , 4.75, -5. , -5. , -5. , -5. , 0. , 0. ])` Our actual output is: `array([ 0. , -2.5 , -4.75, 5. , 5. , 5. , 5. , 0. , 0. ])`
> 
> All other outputs match the suggested outputs in the examples in the documentation.

You're right - the comment for the `Tabulation` class has the correct output but the README is wrong.

2024-09-12 19:44 UTC, esimpsons3ti commented
Within the main docstring for `Tabulation`, there are instances of double colons.

```
    In general, zero values (either supplied or computed) at either the leading or
    trailing ends are removed. However, if explicitly supplied, one leading and/or
    trailing zero value is considered significant because it anchors the interpolation of
    a ramp at the beginning or end of the domain. For example::
```

2024-09-12 19:45 UTC, mace-space commented
Sphinx documentation (`docs/_build/html/index.html`)
- It might be preferable for links such as [PDS Ring-Moon Systems Node](https://pds-rings.seti.org/) open up in a separate new tab
- Several links give 404 errors, e.g. the module documentation and Contributing Guide links (e.g. the former links to https://rms-.readthedocs.io/en/latest/module.html ; and the latter example links to https://github.com/SETI/rms-/blob/main/CONTRIBUTING.md instead of https://github.com/SETI/rms-tabulation/blob/main/CONTRIBUTING.md).

2024-09-12 19:48 UTC, rfrenchseti commented
> Within the main docstring for `Tabulation`, there are instances of double colons.
> 
> ```
>     In general, zero values (either supplied or computed) at either the leading or
>     trailing ends are removed. However, if explicitly supplied, one leading and/or
>     trailing zero value is considered significant because it anchors the interpolation of
>     a ramp at the beginning or end of the domain. For example::
> ```

Double colons are a Sphinx directive that says that the next block of text should be code instead of formatted text. It's the only way to get Sphinx to enforce line breaks in examples. I agree it looks odd in the raw text, but then so do a lot of Sphinx directives like back-quotes.

2024-09-12 19:50 UTC, esimpsons3ti commented
So this is for when the docstring of the `Tabulation` class itself is put through Sphinx?

2024-09-12 19:51 UTC, rfrenchseti commented
> So this is for when the docstring of the `Tabulation` class itself is put through Sphinx?

Yes, like when the readthedocs.io page is constructed. If you create the Sphinx documentation on your local machine as described above and then click on the "tabulation module" link to get the descriptions of the classes/methods, you'll see how that text ends up getting formatted.

2024-09-12 19:55 UTC, rfrenchseti commented
> Sphinx documentation (`docs/_build/html/index.html`)
> 
> * It might be preferable for links such as [PDS Ring-Moon Systems Node](https://pds-rings.seti.org/) open up in a separate new tab
> * Several links give 404 errors, e.g. the module documentation and Contributing Guide links (the former links to https://rms-.readthedocs.io/en/latest/module.html ; and the latter example links to https://github.com/SETI/rms-/blob/main/CONTRIBUTING.md instead of https://github.com/SETI/rms-tabulation/blob/main/CONTRIBUTING.md).

reStructuredText actually explicitly doesn't open pages in new tabs (it's their design decision on how documentation should work, and it's a real pain to convince it to do so.

Good catch on the bad URLs. (Although even if I fixed them now they still wouldn't actually work since the documentation isn't on readthedocs until we merge this pull)

2024-09-20 22:25 UTC, mace-space commented
In the `fwhm` function, the `fraction` parameter is allowed to be any value. Although I think for any value outside of [0,1], the `ValueError: Tabulation does not cross fractional height twice` would be raised, might it be more informative to the user to catch this earlier with a more specific error message?

2024-09-20 23:09 UTC, mace-space requested changes
Some minor changes to address (described in comments on the PR).

2024-09-30 22:54 UTC, mace-space approved these changes
Looks good

2024-09-30 23:35 UTC, merged